#DataSource & HikariCP 설정
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://{ DB 호스트 }:{ DB 포트 }/{ DB명 }?serverTimezone=Asia/Seoul
    username: { username }
    password: { password }
    hikari:
      connection-test-query: SELECT NOW() FROM dual
      connection-timeout: 30000
      validation-timeout: 30000
      minimum-idle: 5
      max-lifetime: 240000
      maximum-pool-size: 20
  jpa:
    open-in-view: true
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: com.study.jpatransaction.strategy.CustomCamelCaseToSnakeNamingStrategy
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: false

logging:
  level:
    org:
      springframework:
        transaction: trace
        orm:
          jpa: debug
      hibernate:
        SQL: info
    root: info
    com:
      zaxxer:
        hikari:
          pool:
            HikariPool: debug